### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Telemain** [Parzivail-Modding-Team/ParziStarWarsMod#1]
Crash log: http://pastebin.com/Xq04m9sf

I have a lot of mods but the crash seems ParziStarWars specific and doesn't occur without it.

**Comment by parzivail** [comment]
I don't think that ParziStarWarsMod plays well with Cauldron, but we're working on making it as compatible as possible, so an update this afternoon should include a fix :D

**Comment by Telemain** [comment]
Thanks!
