### ISSUE TITLE
Cannot complete arrest mission (Imperial Questline)

### ISSUE THREAD

**Issue by Yakna** [Parzivail-Modding-Team/ParziStarWarsMod#10]
I cannot complete the mission where i have to scan people and arrest them if they're suspicious. I scanned everybody, but i don't know how to use the Scanner correctly, as everybody has the blue text. And from the arrest part, how exactly i do that?

**Comment by TheDarkestKnight1939** [comment]
1. If you find someone, he'll become handcuffed, this means he's arrested. 
2. You just have to keep trying. Sooner or later you'll find someone. It's pure luck.

**Comment by Yakna** [comment]
and how i can see if he is a rebel? The name will be red? Or what?

**Comment by TheDarkestKnight1939** [comment]
Exactly
