### ISSUE TITLE
HyperDrive to Earth spawn location

### ISSUE THREAD

**Issue by securitypedant** [Parzivail-Modding-Team/ParziStarWarsMod#11]
I've two suggestion here.

1. When returning to the Overworld (Earth) it would be nice to have a customizable spawn location. My server uses Forgeessentials and it has allowed me to change the spawn location for all new players. I've built an entire city around this new location. When returning to Earth in Star Wars, I spawn a long way from my main playing area.

2. Even better would be to spawn each player at the location where they originally left Earth. Galacticraft is like this. When I fly to the moon and return back to Earth, I land in the same area that I took off from. Would be great to return to Earth in the same place that I left.

However I do think that the spawn points for other planets should be fixed. Because obviously heading to Tatooine I should end up in the city, not the place I was last. Unless you implement a custom HyperDrive where I can travel to any location I desire.

**Comment by parzivail** [comment]
Great suggestion! We'll keep this in mind. However, we'll be revamping hyperdrives soon, so t=stay tuned!
