### ISSUE TITLE
Does Anyone Know Where To Start The Jedi Questline?

### ISSUE THREAD

**Issue by CmdrNorthpaw** [Parzivail-Modding-Team/ParziStarWarsMod#11]
I just got the mod, and have decided to become a Jedi, mainly so I can use the Force in Middle Earth using my Lord of the Rings mod. However, I haven't been able to find where he lives, so can someone tell me the xyz coordinates?

**Comment by parzivail** [comment]
[Here's the official map.](http://parzivail.com/mods/tswm/images/maps/Tatooine%20Map.png)
