### ISSUE TITLE
Server crash by mobs

### ISSUE THREAD

**Issue by maskenms** [Parzivail-Modding-Team/ParziStarWarsMod#12]
Hello. 1.2.1 version. Crash server by mobs. Thank.
[crash-2015-12-28_10.59.14-server.txt](https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/files/74211/crash-2015-12-28_10.59.14-server.txt)
[crash-2015-12-29_17.57.57-server.txt](https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/files/74212/crash-2015-12-29_17.57.57-server.txt)
[crash-2015-12-29_19.24.40-server.txt](https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/files/74213/crash-2015-12-29_19.24.40-server.txt)
[crash-2015-12-29_20.20.57-server.txt](https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/files/74214/crash-2015-12-29_20.20.57-server.txt)

**Comment by parzivail** [comment]
Mod does not work with Cauldron or CraftBukkit, consider using a pure Forge server.
