### ISSUE TITLE
how to become a sith?

### ISSUE THREAD

**Issue by ArePorgsWeird** [Parzivail-Modding-Team/ParziStarWarsMod#13]
so i've been playing on a private server with some friends and we can't figure out how to become a sith.
we know you need to be level 35 but what are the actual steps to becoming one.
the wiki page is kinda vague.

**Comment by AlvaroLuqman** [comment]
find the sith questmaster in mos eisley

**Comment by Furypit** [comment]
You gotta first become a jedi, to do so start the jedi questline outside of Mos Eisley and then do as the wiki says
