### ISSUE TITLE
1.2.1 running on server, but client side asks for 1.2.0

### ISSUE THREAD

**Issue by Momibelle** [Parzivail-Modding-Team/ParziStarWarsMod#14]
We are running the latest server build 1.2.1, but when a random (about 5% of those who try to join) client joins, is rejected because the server asks for 1.2.0

We also see the version as '1.2.0' while in-game (top LH corner GUI) but know we are running 1.2.1

: )
Still awesome as ever!

**Comment by parzivail** [comment]
when I built 1.2.1, I forgot to change the version number from 1.2.0 to 1.2.1. the actual mod changes are there, but ensure all of the filenames everyone has are the same, because until I can push a patch, thats the only way to tell

**Comment by FilamorKnight** [comment]
i got Problem for installing this mod 
How i install This Mod
it wont appear on my ModList

**Comment by weastonmiller** [comment]
@FilamorKnight Can you give us more information? We've never had that problem before.

**Comment by Momibelle** [comment]
This appears to be happening about 1 out of 20 times (tested in a room full of computers while modding them). We use Multi-MC, and we double-checked the forge version. Downloaded from both the mirror site and reg site. Rebooted, and still could not get one computer to load the mod. FilamorKnight, maybe check your version of Forge, first?
