### ISSUE TITLE
Client crash when connecting to server or loading singleplayer 

### ISSUE THREAD

**Issue by ShotgunKitty** [Parzivail-Modding-Team/ParziStarWarsMod#15]
The title says it, crashing with light blue screen. I will attach a crash-report.

[crash-2015-12-28_23.14.36-client.txt](https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/files/74899/crash-2015-12-28_23.14.36-client.txt)

**Comment by parzivail** [comment]
It seems the mod is incompatible with `weather2` (Weather-2.3.4.jar), it should run smoothly if you remove the jar from the mods folder. We've been experiencing a lot of similar crashes recently and are diligently working on a fix.

**Comment by ShotgunKitty** [comment]
Yeah weather 2 was the problem I removed it and now everything works fine thanks ;)
