### ISSUE TITLE
please help...

### ISSUE THREAD

**Issue by zachu16** [Parzivail-Modding-Team/ParziStarWarsMod#15]
could anyone write the goals of all missions from master yoda?

**Comment by AlvaroLuqman** [comment]
I know I'm late and you probably know this already but I just want to share.
The missions are:
1. Learn how to use 'Force Grab' on hostiles/enemy. You need to level up your Holocron level (by killing mobs) and the higher the level, the more mobs you need to kill to go to the next level) and every time you level up you gain 1 upgrade point which is used to study the force powers, so it might take time. Once done go back to Yoda for 2nd mission
2. You will be given an Ilum Hyperdrive to make your first lightsaber. Once you arrive at ilum, you'll need to find the kyber crystal and focusing crystal, found in the caves of ilum, and craft the needed materials for the lightsaber. The lightsaber forge table is located on the upper level of the temple. Once you have ur lightsaber, return to yoda.(Further info of how to craft  the lightsaber is available in the official website)
3. Yoda will tell a bunch of paragraphs about the Dark Side and once he said all that, your quest is basically done. You can keep leveling up and earn the rank of a Jedi master.




NOTES: - The rarity of the least rarest kyber crystals (blue and green) is as rare as a diamond ore, so it might take time finding one.
            - The cave to find the kyber crystal and the focusing crystal is located at the lowest level of the Temple. The cave has an icy entrance.
