### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by KadeWolfe** [Parzivail-Modding-Team/ParziStarWarsMod#17]
The game crashes every time I try to go to wild space. As a result, I am unable to complete my further rebel quests nor take up new quests. Please let me know if there is any way to fix this or if I can somehow spawn the quest NPCs from Ba-Sing station and complete the wild space quest. Thank you!

**Comment by DreadLordGaming** [comment]
it because you ran out of memory on your game 
i had the same problem
