### ISSUE TITLE
Mobs not spawning

### ISSUE THREAD

**Issue by securitypedant** [Parzivail-Modding-Team/ParziStarWarsMod#17]
Mobs are not spawning in any biome. If I give myself a Jawa spawn egg, I can spawn them. I also have other mods that spawn mobs without issue. I have the following mods on the server, I am also running forge-1.7.10-10.13.4.1558-1.7.10-universal.jar ..

[1-7-10]_Lucky_Block_v5-1-0.jar
1.7.10-MB_Battlegear2-Bullseye-1.0.8.2.jar
[1.7.10]Treecapitator-universal-2.0.4.jar
archimedesshipsplus-1.7.10-1.8.jar
backpack-2.0.1-1.7.x.jar
Baubles-1.7.10-1.0.1.10.jar
Botania r1.8-246.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
Decocraft-2.2.1_1.7.10.jar
DoggyStyle-1.1.3.99.jar
ExtraDoors-1.7.2-1.5.1.jar
extrautilities-1.2.12.jar
forgeessentials-1.7.10-1.4.3.1021-server.jar
GalacticraftCore-1.7-3.0.12.375.jar
Galacticraft-Planets-1.7-3.0.12.375.jar
Hats-4.0.1.jar
iChunUtil-4.0.0.jar
InventoryTweaks-1.58-147.jar
MCA-1.7.10-5.1.1.0-universal.jar
MicdoodleCore-1.7-3.0.12.375.jar
Morph-Beta-0.9.2.jar
MoVillages-1.3.1.jar
movingworld-1.7.10-1.8.jar
MrCrayfishFurnitureModv3.4.8(1.7.10).jar
NotEnoughItems-1.7.10-1.0.5.111-universal.jar
Parzi's Star Wars Mod v1.2.1.jar
RadixCore-1.7.10-2.1.1-universal.jar
Ruins-1.7.10.jar
Transformers-1.7.10-0.5.10.jar
twiliocraft-1.1.jar
twilio-java-sdk-5.6.0-jar-with-dependencies.jar
worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar

**Comment by securitypedant** [comment]
Here are the logs from the server. I see some exceptions in there, not sure if they are related.
[logs.zip](https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/files/76029/logs.zip)

**Comment by securitypedant** [comment]
I also took a look at the following class.

https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/blob/5a31bde471849209b3875dd7312b900f7108bf84/src/main/java/com/parzi/starwarsmod/registry/WorldRegister.java

And noticed a whole load of BiomeManager.removeSpawnBiome(StarWarsMod.biomeTatooine);

Is this related? Are you removing the spawn functionality from those biomes?

**Comment by weastonmiller** [comment]
That code is actually old, we haven't pushed the source in a while because we keep making major changes, so none of that code is the same in 1.2.1, at least I don't think it is, but we'll check it out and get a fix in with 1.2.5.  Sorry for the inconvenience.

**Comment by securitypedant** [comment]
Ahh ok :) if you push the latest code to GitHub, I can maybe recreate a test debug environment and provide more detailed feedback. I was also thinking I might contribute if you need extra dev help.

**Comment by weastonmiller** [comment]
@securitypedant Thanks for the willingness to help, but we're a little too deep (and not de-bugged enough) into 1.2.5 to push the source and not have it crash from unfinished new things.  We'll try to push it with the new release though.  Seriously thanks for being willing to help, most people just expect a fix and don't want to test, we'll let you know if we need any help with anything

**Comment by parzivail** [comment]
I'll see if i can manage a patch in the next update, thanks for the help with finding thr bug :D

**Comment by securitypedant** [comment]
No worries guys, its easy for me to backup my server and run a debug build in Eclipse if you need extra QA.This mod has a lot of potential, more than happy to lend a hand. Just tell me when and where.

**Comment by parzivail** [comment]
@securitypedant A new update, 1.2.5-beta, just came out, see if that fixed your issue ^-^

**Comment by securitypedant** [comment]
Thanks man, will download tomorrow. BTW did you JUST put the jar file up and not actually push the code to the repo? Would be nice to see the code hit the repo so I can help debug anything if it goes wrong.

**Comment by parzivail** [comment]
@securitypedant We're waiting for the beta to end, and for 1.2.5 to be released as a stable release before we push the code. There're a few secrets we don't want getting out about 1.2.5 ^-^

**Comment by parzivail** [comment]
@securitypedant We think that 1.2.5-final fixes this, but we're still gonna push the code with the new release (hopefully very soon)

**Comment by parzivail** [comment]
@securitypedant Just pushed both the code and a patch-release (1.2.6). We re-wrote mobs, so this may fix your issue, but feel free to take a look ^-^
