### ISSUE TITLE
Client Crash after runnning for a few minutes 

### ISSUE THREAD

**Issue by d34dj3d1** [Parzivail-Modding-Team/ParziStarWarsMod#18]
This is just one of the crashes i've had since updating to 1.2.1. I just had one a few minutes ago that seemed to be conflicting with DrZharks MoCreatures Mod v6.3.1

---- Minecraft Crash Report ----

// Surprise! Haha. Well, this is awkward.

Time: 1/3/16 3:51 PM

Description: Rendering entity in world

java.lang.ClassCastException:
net.ilexiconn.llibrary.client.render.entity.RenderLLibraryEntity cannot
be cast to com.parzi.starwarsmod.rendering.helper.PSWMEntityRenderer

at com.parzi.starwarsmod.handlers.ClientEventHandler.onRender(ClientEventHandler.java:218)

at cpw.mods.fml.common.eventhandler.ASMEventHandler_440_ClientEventHandler_onRender_Pre.invoke(.dynamic)

at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)

at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)

at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:71)

at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:23)

at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:11)

at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)

at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)

at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)

at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471)

at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)

at net.ilexiconn.llibrary.client.render.entity.RenderLLibraryEntity.func_78480_b(RenderLLibraryEntity.java:29)

at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)

at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)

at net.minecraft.client.main.Main.main(SourceFile:148)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:483)

at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------

-- Head --

Stacktrace:

at com.parzi.starwarsmod.handlers.ClientEventHandler.onRender(ClientEventHandler.java:218)

at cpw.mods.fml.common.eventhandler.ASMEventHandler_440_ClientEventHandler_onRender_Pre.invoke(.dynamic)

at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)

at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)

at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:71)

at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:23)

at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:11)

-- Entity being rendered --

Details:

Entity Type: Spider (net.minecraft.entity.monster.EntitySpider)

Entity ID: 13418

Entity Name: Spider

Entity's Exact location: -1270.48, 205.00, 1112.69

Entity's Block location: World: (-1271,205,1112), Chunk: (at 9,12,8
in -80,69; contains blocks -1280,0,1104 to -1265,255,1119), Region:
(-3,2; contains chunks -96,64 to -65,95, blocks -1536,0,1024 to
-1025,255,1535)

Entity's Momentum: 0.00, -0.08, 0.04

-- Renderer details --

Details:

Assigned renderer: net.minecraft.client.renderer.entity.RenderSpider@17f9d4f4

Location: -19.61,-1.62,-14.11 - World: (-20,-2,-15), Chunk: (at
12,-1,1 in -2,-1; contains blocks -32,0,-16 to -17,255,-1), Region:
(-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to
-1,255,-1)

Rotation: -60.52842

Delta: 0.05632758

Stacktrace:

at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)

at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)

at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)

at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471)

at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)

-- Affected level --

Details:

Level name: MpServer

All players: 1 total; [EntityClientPlayerMP['D34dJ3d1'/10661, l='MpServer', x=-1250.89, y=206.62, z=1126.62]]

Chunk stats: MultiplayerChunkCache: 25, 25

Level seed: 0

Level generator: ID 00 - default, ver 1. Features enabled: false

Level generator options:

Level spawn location: World: (-944,64,1004), Chunk: (at 0,4,12 in
-59,62; contains blocks -944,0,992 to -929,255,1007), Region: (-2,1;
contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)

Level time: 12154140 game time, 13536976 day time

Level dimension: 0

Level storage version: 0x00000 - Unknown?

Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)

Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false

Forced entities: 53 total; [EntityClientPlayerMP['D34dJ3d1'/10661,
l='MpServer', x=-1250.89, y=206.62, z=1126.62],
MoCEntitySnail['Snail'/10663, l='MpServer', x=-1273.44, y=68.00,
z=1121.44], MoCEntityMouse['Mouse'/10664, l='MpServer', x=-1283.47,
y=66.00, z=1121.56], EntityItem['item.tile.sapling.oak'/10665,
l='MpServer', x=-1281.16, y=95.13, z=1129.13],
EntityItem['item.tile.sapling.oak'/10666, l='MpServer', x=-1284.13,
y=109.13, z=1135.91], EntityItem['item.item.apple'/10667, l='MpServer',
x=-1283.81, y=108.13, z=1131.88],
EntityItem['item.tile.sapling.oak'/10668, l='MpServer', x=-1294.59,
y=115.13, z=1134.88], EntityItem['item.tile.sapling.oak'/10669,
l='MpServer', x=-1295.91, y=113.13, z=1133.84],
MoCEntityWerewolf['Werewolf'/10670, l='MpServer', x=-1262.50, y=6.00,
z=1103.50], EntityItem['item.tile.sapling.oak'/10671, l='MpServer',
x=-1264.13, y=97.13, z=1167.13], EntityPig['Pig'/10672, l='MpServer',
x=-1278.22, y=64.00, z=1089.78], EntityItem['item.tile.torch'/10673,
l='MpServer', x=-1237.50, y=50.13, z=1165.47],
EntityItem['item.tile.sapling.oak'/10674, l='MpServer', x=-1242.63,
y=50.13, z=1164.44], EntityItem['item.tile.sapling.oak'/10675,
l='MpServer', x=-1245.50, y=50.13, z=1167.03],
EntityItem['item.item.apple'/10676, l='MpServer', x=-1284.13, y=100.13,
z=1161.66], MoCEntityHorse['WildHorse'/10677, l='MpServer', x=-1289.44,
y=68.00, z=1095.56], EntityChicken['Chicken'/10678, l='MpServer',
x=-1293.81, y=68.00, z=1103.81],
EntityItem['item.tile.colorizedSaplings.sacredoakSapling'/10679,
l='MpServer', x=-1285.03, y=236.13, z=1091.13],
EntityItem['item.tile.colorizedSaplings.sacredoakSapling'/10680,
l='MpServer', x=-1285.66, y=235.13, z=1092.03],
EntityCreeper['Creeper'/10681, l='MpServer', x=-1220.50, y=4.00,
z=1152.50], EntitySkeleton['Skeleton'/10682, l='MpServer', x=-1216.50,
y=31.00, z=1152.00], EntityItem['item.tile.torch'/10683, l='MpServer',
x=-1220.53, y=50.13, z=1166.88],
EntityItem['item.tile.sapling.oak'/10684, l='MpServer', x=-1220.22,
y=50.13, z=1167.75], MoCEntityMouse['Mouse'/10685, l='MpServer',
x=-1201.72, y=22.92, z=1120.56], EntityPig['Pig'/10686, l='MpServer',
x=-1264.13, y=60.92, z=1168.78], EntityPig['Pig'/10687, l='MpServer',
x=-1264.13, y=60.92, z=1170.72], EntityItem['item.item.apple'/10688,
l='MpServer', x=-1276.13, y=42.12, z=1172.78],
EntityItem['item.tile.sapling.oak'/10689, l='MpServer', x=-1275.78,
y=44.12, z=1172.88], EntityItem['item.tile.sapling.oak'/10690,
l='MpServer', x=-1265.13, y=44.12, z=1178.88],
MoCEntityDragonfly['DragonFly'/10691, l='MpServer', x=-1273.28,
y=207.92, z=1087.28], EntityZombie['Zombie'/10692, l='MpServer',
x=-1215.31, y=26.92, z=1148.31], EntitySkeleton['Skeleton'/10693,
l='MpServer', x=-1215.53, y=29.92, z=1142.94], EntityCow['Cow'/10703,
l='MpServer', x=-1239.25, y=47.42, z=1176.41],
EntityItem['item.tile.sapling.oak'/10704, l='MpServer', x=-1280.34,
y=43.16, z=1179.81], MoCEntityFishy['Fishy'/10705, l='MpServer',
x=-1311.98, y=59.22, z=1104.39], MoCEntityMouse['Mouse'/10706,
l='MpServer', x=-1311.56, y=61.92, z=1096.81],
MoCEntityMouse['Mouse'/10707, l='MpServer', x=-1311.94, y=61.92,
z=1094.47], EntityItem['item.item.porkchopRaw'/10708, l='MpServer',
x=-1281.19, y=-3.88, z=1085.81],
EntityItem['item.tile.colorizedSaplings.sacredoakSapling'/10709,
l='MpServer', x=-1292.53, y=-2.88, z=1083.88],
EntityChicken['Chicken'/10710, l='MpServer', x=-1293.44, y=64.15,
z=1086.56], EntityCartChest['entity.MinecartChest.name'/10711,
l='MpServer', x=-1214.50, y=30.50, z=1098.50],
EntityItem['item.tile.colorizedSaplings.sacredoakSapling'/10712,
l='MpServer', x=-1210.25, y=182.12, z=1092.13],
EntityItem['item.tile.colorizedSaplings.sacredoakSapling'/10713,
l='MpServer', x=-1212.88, y=185.12, z=1092.75],
EntityItem['item.tile.colorizedSaplings.sacredoakSapling'/10714,
l='MpServer', x=-1214.78, y=185.12, z=1097.94],
EntityCartChest['entity.MinecartChest.name'/10715, l='MpServer',
x=-1208.50, y=34.50, z=1162.50],
EntityCartChest['entity.MinecartChest.name'/10716, l='MpServer',
x=-1208.50, y=34.50, z=1162.50], MoCEntityCricket['Cricket'/10725,
l='MpServer', x=-1302.53, y=63.96, z=1087.75],
EntityItem['item.tile.colorizedSaplings.sacredoakSapling'/10726,
l='MpServer', x=-1210.84, y=179.12, z=1083.81],
EntityItem['item.tile.colorizedSaplings.sacredoakSapling'/10727,
l='MpServer', x=-1213.22, y=181.12, z=1085.66],
EntityItem['item.tile.colorizedSaplings.sacredoakSapling'/10728,
l='MpServer', x=-1215.53, y=183.12, z=1086.06],
EntitySkeleton['Skeleton'/10729, l='MpServer', x=-1204.09, y=16.14,
z=1182.97], EntitySpider['Spider'/13418, l='MpServer', x=-1270.48,
y=205.00, z=1112.69], EntitySpider['Spider'/13419, l='MpServer',
x=-1270.53, y=205.00, z=1107.66]]

Retry entities: 0 total; []

Server brand: fml,forge

Server type: Integrated singleplayer server

Stacktrace:

at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)

at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)

at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)

at net.minecraft.client.main.Main.main(SourceFile:148)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:483)

at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --

Details:

Minecraft Version: 1.7.10

Operating System: Windows 7 (amd64) version 6.1

Java Version: 1.8.0_25, Oracle Corporation

Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

Memory: 490765600 bytes (468 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)

JVM Flags: 6 total;
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode
-XX:-UseAdaptiveSizePolicy -Xmn128M

AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used

IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94

FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 133 mods loaded, 133 mods active

States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' =
Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available
'D' = Disabled 'E' = Errored

UCHIJAAAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)

UCHIJAAAA FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10.jar)

UCHIJAAAA Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10.jar)

UCHIJAAAA FR-CORE{1.0.3} [Floatable Rails] (minecraft.jar)

UCHIJAAAA ivtoolkit{IvToolkit} [1.2] (minecraft.jar)

UCHIJAAAA OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar)

UCHIJAAAA TooManyItems{1.7.10} [TooManyItems] (minecraft.jar)

UCHIJAAAA <CoFH ASM>{000} [CoFH ASM] (minecraft.jar)

UCHIJAAAA <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar)

UCHIJAAAA zeldaswordskills{1.7.10-2.3.1} [Zelda Sword Skills] (1.7.10-zeldaswordskills-2.3.1.jar)

UCHIJAAAA DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar)

UCHIJAAAA bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar)

UCHIJAAAA DirectionHUD{1.24} [DirectionHUD] ([1.7.10]DirectionHUD-client-1.24.jar)

UCHIJAAAA Sentries{1.7.2} [Sentries] ([1.7.10]Sentries.jar)

UCHIJAAAA StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar)

UCHIJAAAA animalsPlus{1.2} [Animals+] (animalsPlus-1.2.jar)

UCHIJAAAA AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10.jar)

UCHIJAAAA antiqueatlas{4.2.7-1.7.10} [Antique Atlas] (antiqueatlas-4.2.7-1.7.10.jar)

UCHIJAAAA aquaticabyss{1.1.1} [Aquatic Abyss] (Aquatic-Abyss-Mod-1.7.10.jar)

UCHIJAAAA AquaTweaks{1.0} [AquaTweaks] (AquaTweaks-1.7.10-1.0.jar)

UCHIJAAAA BetterFoliage{1.0.15} [Better Foliage] (BetterFoliage-mc1.7-1.0.15.jar)

UCHIJAAAA BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar)

UCHIJAAAA malisiscore{1.7.10-0.14.0} [MalisisCore] (malisiscore-1.7.10-0.14.0.jar)

UCHIJAAAA malisisdoors{1.7.10-1.13.0} [Malisis' Doors] (malisisdoors-1.7.10-1.13.0.jar)

UCHIJAAAA BigDoors{1.7.10-1.0.0} [Big Doors] (BigDoors-1.7.10-1.0.0.jar)

UCHIJAAAA bigtrees{1.7.2b} [The BigTrees Mod] (BigTrees-172b-forge1060.jar)

UCHIJAAAA BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1578-universal.jar)

UCHIJAAAA buildhelper{1.0.0} [Build Helper] (BuildHelper_v1.0.0.jar)

UCHIJAAAA CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar)

UCHIJAAAA cheshirecat{2.5} [Cheshire Cat Builder's Helper] (cheshirecat-builders-helper-mc1.7.10-2.5.jar)

UCHIJAAAA Chimneys{1.7.2} [Chimneys] (Chimneys-Mod-1.7.10.jar)

UCHIJAAAA CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar)

UCHIJAAAA BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar)

UCHIJAAAA CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar)

UCHIJAAAA CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar)

UCHIJAAAA ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar)

UCHIJAAAA ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar)

UCHIJAAAA CraftHeraldry{1.1.3} [CraftHeraldry] (CraftHeraldry 1.1.3.jar)

UCHIJAAAA CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip)

UCHIJAAAA PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.2.1_1.7.10.jar)

UCHIJAAAA props{2.2.1} [Decocraft] (Decocraft-2.2.1_1.7.10.jar)

UCHIJAAAA DeepSeaDiving{1.1.0} [DeepSeaDiving] (Deep Sea Diving 1.1.zip)

UCHIJAAAA divblocks{1.1} [DivBlocks] (DivBlocks-1.7.10-1.1.jar)

UCHIJAAAA grim3212core{V0.1 - 1.7.10} [Grim3212 Core] (Grim3212 Core-V0.1 - 1.7.10.jar)

UCHIJAAAA doubledoors{V0.1 - 1.7.10} [Double Doors] (Double-doors-mod-by-derbam-1.7.10.jar)

UCHIJAAAA Forestry{4.2.4.52} [Forestry for Minecraft] (forestry_1.7.10-4.2.4.52.jar)

UCHIJAAAA DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V10d.jar)

UCHIJAAAA MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip)

UCHIJAAAA dualhotbar{1.6} [Dual Hotbar] (dualhotbar-1.7.10-1.6.jar)

UCHIJAAAA dungeonmobs{4.1.3} [Dungeon Mobs] (Dungeon Mobs v4.1.3.jar)

UCHIJAAAA SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar)

UCHIJAAAA DynamicTransport{0.1.2.0} [Dynamic Transport] (Dynamic-Transport-Mod-1.7.10.jar)

UCHIJAAAA DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar)

UCHIJAAAA DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar)

UCHIJAAAA DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar)

UCHIJAAAA DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar)

UCHIJAAAA DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar)

UCHIJAAAA DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar)

UCHIJAAAA DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar)

UCHIJAAAA DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar)

UCHIJAAAA DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar)

UCHIJAAAA DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar)

UCHIJAAAA etfuturum{1.4.4} [Et Futurum] (Et Futurum-1.4.4.jar)

UCHIJAAAA ExpandedRedstone{1.0} [Expanded Redstone] (ExpandedRedstone 1.7.10 V10b.jar)

UCHIJAAAA examplemod{1.0} [examplemod] (ExtraDoors-1.7.2-1.5.1.jar)

UCHIJAAAA extradoors{1.5.1} [Extra Doors] (ExtraDoors-1.7.2-1.5.1.jar)

UCHIJAAAA fairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar)

UCHIJAAAA fandomcraft{4.1.1} [FandomCraft] (Fandomcraft-4.1.5-Universal.jar)

UCHIJAAAA extinguisher{V0.1 - 1.7.10} [Extinguisher] (Fire-Extinguisher-Mod-1.7.10.jar)

UCHIJAAAA fireplaces{V0.1 - 1.7.10} [Fireplaces] (Fireplace-Mod-1.7.10.jar)

UCHIJAAAA floatingrails{1.0.0} [Floating Rails] (FloatingRails-1.3.1 Alpha 1.7.Universal.jar)

UCHIJAAAA FloodLights{1.0.3-116} [Flood Lights] (FloodLights-1.7.10-1.0.3-116.jar)

UCHIJAAAA frames{V0.1 - 1.7.10} [Frames] (Frames-Mod-1.7.10.jar)

UCHIJAAAA GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar)

UCHIJAAAA GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar)

UCHIJAAAA GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar)

UCHIJAAAA GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar)

UCHIJAAAA HelperToolsID{v1.6f} [HelperTools] (HelperTools-1.7.10-v1.6f.jar)

UCHIJAAAA ihouse{2.6} [iHouse Mod] (ihouse-2.6.jar)

UCHIJAAAA InGameModConfigs{1.0.0.1} [InGame Mod Configs] (InGameModConfigs-1.7.10-1.0.0.1-client.jar)

UCHIJAAAA instahouse{7.5} [Insta House] (InstaHousev7.5.jar)

UCHIJAAAA instantblocks{1.5.4} [Instant Blocks] (InstantBlocks_v1.5.4.jar)

UCHIJAAAA journeymap{5.1.3} [JourneyMap] (journeymap-1.7.10-5.1.3-unlimited.jar)

UCHIJAAAA koresample{1.7.10-1.3.2} [Kore Sample] (KoreSample-1.7.10-1.3.2.jar)

UCHIJAAAA latticemod{1.0} [Lattice Mod] (Lattice-Mod-1.7.10.jar)

UCHIJAAAA llibrary{0.6.2} [LLibrary] (llibrary-0.6.2-1.7.10.jar)

UCHIJAAAA LotsOfFood{1.7.10} [Lots of Food] (Lots of Food-1.7.10 v7.jar)

UCHIJAAAA LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar)

UCHIJAAAA lycanitesmobs{1.13.0.3 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA arcticmobs{1.13.0.3 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA demonmobs{1.13.0.3 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA desertmobs{1.13.0.3 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA forestmobs{1.13.0.3 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA freshwatermobs{1.13.0.3 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA infernomobs{1.13.0.3 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA junglemobs{1.13.0.3 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA mountainmobs{1.13.0.3 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA plainsmobs{1.13.0.3 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA saltwatermobs{1.13.0.3 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA shadowmobs{1.13.0.3 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA swampmobs{1.13.0.3 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.3 [1.7.10].jar)

UCHIJAAAA modularpots{1.7.10.14} [Modular Flower Pots] (ModularPots-1.7.10.14.jar)

UCHIJAAAA cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar)

UCHIJAAAA MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar)

UCHIJAAAA openfm{0.1.0.14} [OpenFM] (OpenFM-0.1.0-14.jar)

UCHIJAAAA harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar)

UCHIJAAAA temperateplants{1.7.2b} [Pam's Temperate Plants] (Pam's Temperate Plants 1.7.2b.zip)

UCHIJAAAA starwarsmod{1.2.0} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.2.0.jar)

UCHIJAAAA plantmegapack{4.30} [Plant Mega Pack] (plantmegapack-4.30-1.7.10-1492.jar)

UCHIJAAAA cuchaz.powerTools{1.7.10-1.3} [Power Tools] (powerTools-v1.7.10-1.3.jar)

UCHIJAAAA BridgeRails{3.0.0} [Rail Bridges] (Rail-Bridges-Mod-1.7.10.jar)

UCHIJAAAA Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar)

UCHIJAAAA RedstonePasteMod{1.6.2} [Redstone Paste] (Redstone-Paste-Mod-1.7.10.jar)

UCHIJAAAA Schematica{1.7.6.130} [Schematica] (Schematica-1.7.10-1.7.6.130-universal.jar)

UCHIJAAAA secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar)

UCHIJAAAA slabcraftmod{1.7} [Slabcraft] (Slabcraftmod 1.7 - 1.7.10 Forge.jar)

UCHIJAAAA staircraftmod{1.7} [Staircraft] (Staircraftmod 1.7 - 1.7.10 Forge.jar)

UCHIJAAAA StorageDrawers{1.7.10-1.7.5} [Storage Drawers] (StorageDrawers-1.7.10-1.7.5.jar)

UCHIJAAAA TF2Sentry{1.7.10} [TF2 Sentry] (TF2Sentry-1.7.10.jar)

UCHIJAAAA togglerack{V0.1 - 1.7.10} [Toggle Rack] (Toggle-Rack-Mod-1.7.10.jar)

UCHIJAAAA tts{0.6} [Tube Transport System] (TubeTransportSystem_1.7.10-0.6.jar)

UCHIJAAAA TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar)

UCHIJAAAA AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar)

UCHIJAAAA VersionChecker{1.1.9} [Version Checker] (VersionChecker-1.1.9.jar)

UCHIJAAAA wallcraftmod{1.0} [wallcraftmod] (Wallcraftmod 1.0 - 1.7.10 Forge.jar)

UCHIJAAAA weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar)

UCHIJAAAA XPT{1.1.0} [XP Teleporters] (XPTeleporters-1.7.10-1.1.0.jar)

UCHIJAAAA ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)

UCHIJAAAA McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)

UCHIJAAAA ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar)

UCHIJAAAA MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar)

UCHIJAAAA RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar)

UCHIJAAAA ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)

GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399
Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon HD
6900 Series'

CoFHCore: -[1.7.10]3.0.3-303

Launched Version: 1.7.10-Forge10.13.4.1566-1.7.10

LWJGL: 2.9.1

OpenGL: AMD Radeon HD 6900 Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.

GL Caps: Using GL 1.3 multitexturing.

Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.

Anisotropic filtering is supported and maximum anisotropy is 16.

Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'

Type: Client (map_client.txt)

Resource Packs: [Soartex_Fanver.zip, [1.7.10]Delta-NP Smooth 128x128.zip, Misa+.zip, ChromaHills-128x_1.7v11.zip]

Current Language: English (US)

Profiler Position: N/A (disabled)

Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used

Anisotropic Filtering: Off (1)

**Comment by parzivail** [comment]
Fixed in the next update.
