### ISSUE TITLE
I can't use all the hyperdrive

### ISSUE THREAD

**Issue by ghost** [Parzivail-Modding-Team/ParziStarWarsMod#19]

**Comment by ghost** [comment]
I use sneak+ Right click

**Comment by sss1111123** [comment]
Dont tasking. Mod is dead. Hyperdrive is dont working with no buyed Vehicle (Flyable) and it's dont working when you dont having anything transport yet. You're need buy a transport,or teleport on tatooine with keys Sneak + Right Click
