### ISSUE TITLE
Hi, problem in MP

### ISSUE THREAD

**Issue by Kreeky** [Parzivail-Modding-Team/ParziStarWarsMod#2]
hola,
I'm trying this fantastic mod in mp, but I can not even start the server. log: http://pastebin.com/cWRF4fhU
thanks for attentions :)

**Comment by parzivail** [comment]
Hey!
Thanks for giving our mod a go. Sometimes, the internet decided to truncate files (stupid UDP) when they're downloaded, especially from a 3rd party. Try re-downloading from [here](http://parzivail.com/mods/tswm/download.html) and see if that works. If not, post again here and we'll sort something out!

Thanks!

**Comment by Kreeky** [comment]
hi, 
I tried several things: forge used instead of cauldron, changed version of the mod starwars, downloaded again the mod, but the problem is always the same
what version of forge / cauldron should I use?
Crash: http://pastebin.com/khiY2EPa
Crash: http://pastebin.com/Nztw260c

Thanks for your reply!

**Comment by parzivail** [comment]
We've had some bad experienced with Cauldron, so we recommend [this version of forge, here's the installer](http://adfoc.us/serve/sitelinks/?id=271228&url=http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1448-1.7.10/forge-1.7.10-10.13.4.1448-1.7.10-installer-win.exe)

How much RAM are you allocating to the server? A good amount would be anywhere from 4 to 8 GB.

**Comment by Kreeky** [comment]
the latest crash reports have been made with that version of forge server!
dont even start the server, giving problems at that class!
Crash: http://pastebin.com/khiY2EPa
Crash: http://pastebin.com/Nztw260c
4gb of server RAM :(

**Comment by parzivail** [comment]
We'll work on it and post a patch this weekend. Just hang tight :smiley:

**Comment by Kreeky** [comment]
News? :(

**Comment by parzivail** [comment]
Almost there :D patch will be included in the next release, and we're currently hard at work.

**Comment by parzivail** [comment]
Fixed in update 1.1.1! http://goo.gl/GrFWcy Enjoy :D
