### ISSUE TITLE
Mod doesn't work when trying to host a forge server

### ISSUE THREAD

**Issue by Nutscriptnewb** [Parzivail-Modding-Team/ParziStarWarsMod#21]
I've been trying to play this with one of my friends, but everytime I enter the server, the PWSM logo appears in the upper left, I open and see the items in creative, but everytime I try to use them or spawn anything, it doesn't work.
I tried playing it in singleplayer, done the same thing that I did on the server, and I can spawn vehicles, droids, use hyperdrive, etc.
Could someone help, please ?
I'm using forge 10.13.4.1614 for mc 1.7.10 and the 1.2.1 version of the mod.

**Comment by parzivail** [comment]
from where did you download the mod?

**Comment by Nutscriptnewb** [comment]
I downloaded it from http://parzivail.com/mods/tswm/download.html

**Comment by parzivail** [comment]
No problem!
