### ISSUE TITLE
Can't find imperial questline? 

### ISSUE THREAD

**Issue by StarWarsmaster03** [Parzivail-Modding-Team/ParziStarWarsMod#21]
I can't find where the imperial recruiter is. 
Can someone tell me what planet it's on or where i can find it, PLEAASE!!??
Thank you if you can.

**Comment by Furypit** [comment]
First you need a quest log, then you need the Tatooine hyperdrive, the imperial recruiter is in Mos Eisley, more or less in the center of the city, in a big tower-like building, he has an empire logo hovering over him

**Comment by StarWarsmaster03** [comment]
Thanks.
