### ISSUE TITLE
Shield Generator Base Coordinates

### ISSUE THREAD

**Issue by TomBMine** [Parzivail-Modding-Team/ParziStarWarsMod#22]
I can't find the Shield Generator base for the imperial questline. I've tried looking at the map but it doesnt help. Can anyone give me the coordinates that it spawns at?

**Comment by Furypit** [comment]
The shield generator bases are randomly spawned everywhere on Endor, they are the elliptical ones with the wooden roof, and consist in one big room. The antenna you have to repair (if this is the quest you need to complete) is right on the outside, is the one that... Well, has an antenna attached. You can only walk around hoping to find 5 of those, but again, these bases spawn easily

**Comment by TomBMine** [comment]
Sorry, I meant the rebel shield generator on hoth. I apologize for not being specific.

**Comment by Furypit** [comment]
Well then it's even easier! You just have to find a rebel outpost (they are the ones with 4 big "chunks" one attached to the other, you can easily see them if you use the night vision mode in the map), inside there there's a chest with saddles for tauntauns and a lot of "core generators", take five and you're set. 
If you have difficulties finding one of these outposts there should be one south-west of the main rebel base

**Comment by TomBMine** [comment]
Thanks! That helped a lot!

**Comment by Furypit** [comment]
No prob :) feel free to ask anything else if you need
