### ISSUE TITLE
Im confused

### ISSUE THREAD

**Issue by TomatoSaucee** [Parzivail-Modding-Team/ParziStarWarsMod#23]
Where is the start of the jedi questline? I know its in a house "on the outskirts with a man in it" but I have searched all throughout mos'eiesly.

**Comment by TomatoSaucee** [comment]
Well uh nevermind. Im a retard. I didn't look cloesly enough at the questing post.

**Comment by TomatoSaucee** [comment]
Sorry about changing the subject, I found out im a retard and now know it starts on Tatooine, but I don't know where.

**Comment by Furypit** [comment]
It's a bit far from Mos Eisley, I don't remember the exact coordinates (I'll leave the fun to you), I can only tell you that you have to go north-west from Mos Eisley, the house looks similar to a single home in the desert, but is slightly different
