### ISSUE TITLE
A Few Questions

### ISSUE THREAD

**Issue by messra20** [Parzivail-Modding-Team/ParziStarWarsMod#23]
Concerning the Titanium and the Chromium Ores, at what lvl in the world do they spawn? 
How large are the Ore veins typically for the two ores?

Love what youve done with the mod thus far keep it up.

**Comment by parzivail** [comment]
The ores spawn at every level in the overworld, in veins of one or two. We're overhauling ores in the new update to make them less rare. Thanks!
