### ISSUE TITLE
No Spawn mobs Beta 1.2.5

### ISSUE THREAD

**Issue by Arribaox** [Parzivail-Modding-Team/ParziStarWarsMod#27]
In tatooine the mobs don´t spawn :CC I need Hilt metal, but no only in tatooine in all dimensions please help...

**Comment by parzivail** [comment]
Make sure you're not in peaceful

**Comment by Arribaox** [comment]
yep, difficulty hard... I used The command /cms canspawn PARZIVAIL|jawa to confirm... "Jawa can spawn", The gamerule doMobSpawning it´s true, The same thing happened in the previous version, this patch I waited to see if they fixed, is that they tried, but I do not see that resulted

My mods:
-[1.7.10]Better_Furnaces_V4.3
-backpack-2.0.1-1.7.x
-Better HUD by NukeDuck [1.7.10][1.3.4]
-CodeChickenCore-1.7.10-1.0.4.29-universal
-CustomMobSpawner 3.3.0
-DigitalXP-1.7.10-0.1.5
-DrZharks MoCreatures Mod v6.3.1
-EnchantingPlus-1.7.10-3.0.1
-InventoryTweaks-1.58-147
-ironchest-1.7.10-6.0.62.742-universal
-NotEnoughItems-1.7.10-1.0.4.83-universal
-NotEnoughResources-1.7.10-0.1.0.106
-optifine 1710
-Parzi's Star Wars Mod v1.2.5-beta
-TF2Teleporter-1.7.10
-Thaumcraft-1.7.10-4.2.3.5
-thaumcraftneiplugin-1.7.10-1.7a
-Tree-Capitator-Mod-1.7.10

**Comment by Arribaox** [comment]
I found the solution to the problem
CustomMobSpawner 3.3.0
DrZharks MoCreatures Mod v6.3.1
nots compatible with this mods,I pulled it out and I can play better  
thanks for the help man, you´re the best

**Comment by parzivail** [comment]
No problem, I'll look into better compat with those mods.
