### ISSUE TITLE
PLANETS

### ISSUE THREAD

**Issue by Penwe** [Parzivail-Modding-Team/ParziStarWarsMod#29]
Everytime I try to go to another planet nothing happens and I am using 1.2.5 beta and I am shifting  and right-clicking and i am also crafting it but nothing happens

**Comment by parzivail** [comment]
@Penwe Are there any log messages? If you've changed your keybind, it's not shift-right click, it's sneak-use

**Comment by Penwe** [comment]
There are no key binds

**Comment by parzivail** [comment]
@Penwe Are there any log messages?

**Comment by Momibelle** [comment]
I am getting something similar, and the DIMS are unloading, after we go to a planet:
25.01 23:24:30 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
25.01 23:24:30 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
25.01 23:24:30 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
25.01 23:24:30 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
25.01 23:24:30 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
25.01 23:24:30 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
25.01 23:24:30 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
25.01 23:24:30 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
25.01 23:24:30 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
25.01 23:24:30 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853) [nh.class:?]
25.01 23:24:30 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:507) [mx.class:?]
25.01 23:24:30 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:378) [mx.class:?]
25.01 23:24:30 [Server] INFO at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:172) [add.class:?]
25.01 23:24:30 [Server] INFO at com.parzivail.pswm.items.hyperdrive.ItemHyperdriveTatooine.func_77659_a(ItemHyperdriveTatooine.java:42) [ItemHyperdriveTatooine.class:?]
25.01 23:24:30 [Server] INFO at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:236) [SimpleNetworkWrapper.class:KCauldron-1.7.10-2.1403.1.54]

**Comment by Momibelle** [comment]
I should note: we are using a Cauldron server, with multiverse to manage the DIMS ... not sure if the above log is ample?

**Comment by parzivail** [comment]
@Momibelle @Penwe Hmm, I'll look into this before release.

**Comment by parzivail** [comment]
@Momibelle I'm not entirely positive how compatible the mod is with Cauldron, however, as it is built for native Forge. I'll still look into trying to fix it. How often does it happen? Does it ever crash?

**Comment by Momibelle** [comment]
No it never crashes, just unloads the DIM after you leave it (but it stays loaded if someone remains in that DIM). Also to note: when you move into another DIM, an error appears about the new XP on the JediRobes (can't read it, or something along those lines?) I don't know if that is a connection. 
Once the DIM is unloaded, I have to reboot the server, then it appears again!

**Comment by parzivail** [comment]
@Momibelle I'll check and see what the DIM issue is. Maybe this could be a quick fix ^-^

**Comment by Momibelle** [comment]
Crossing my fingers ... lols ...

**Comment by parzivail** [comment]
@Momibelle I did some digging around, and it looks like it's an issue with Multiverse. It forces the unloading of dimensions to save memory or something. Some claim deleting your `worlds.yml` and re-setting up your worlds *may* fix this issue. (Make a backup, of course :P)

**Comment by Momibelle** [comment]
Thanks for sleuthing! Ya I was thinking about that, too. I'll try that next, thanks!

**Comment by parzivail** [comment]
@Momibelle No prob! Lemme know if that works.

**Comment by Momibelle** [comment]
Deleted the yml file first (fail) then deleted Multiverse itself. DIMS loaded, but the hyperdrives don't work in the game now. Here's the log again after I attempted to use the Tatooine Hyperdrive:

26.01 14:45:23 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
26.01 14:45:23 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
26.01 14:45:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
26.01 14:45:23 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
26.01 14:45:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
26.01 14:45:23 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
26.01 14:45:23 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
26.01 14:45:23 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
26.01 14:45:23 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
26.01 14:45:23 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853) [nh.class:?]
26.01 14:45:23 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:507) [mx.class:?]
26.01 14:45:23 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:378) [mx.class:?]
26.01 14:45:23 [Server] INFO at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:172) [add.class:?]
26.01 14:45:23 [Server] INFO at com.parzivail.pswm.items.hyperdrive.ItemHyperdriveTatooine.func_77659_a(ItemHyperdriveTatooine.java:42) [ItemHyperdriveTatooine.class:?]

**Comment by Momibelle** [comment]
Argh, need to send you the actual log .. looks like it might now be WorldGuard.

**Comment by Momibelle** [comment]
https://www.dropbox.com/s/aviy3dq9pmptmct/2016-01-25-1.log?dl=0

**Comment by Momibelle** [comment]
Pls don't spend too much of your time on this, Colby. I'll continue troubleshooting from this end, assuming that it's misbehaving due to running plugins on a server.
: )

**Comment by parzivail** [comment]
It looks like Cauldron is never running the mod preinitialization stage,
which is where we register both packets (which also handle using
hyperdrives) and losd the config. See if the issues still happen on a
server without cauldron, I think there's a Forge version of WorldGuard too

**Comment by parzivail** [comment]
@Penwe @Momibelle Try it out in 1.2.7

**Comment by Momibelle** [comment]
Yes! Awesome ...

**Comment by Momibelle** [comment]
I mean, let me update and check it out!
