### ISSUE TITLE
Client crashes on multiplayer when right-clicking droid

### ISSUE THREAD

**Issue by tolchuk** [Parzivail-Modding-Team/ParziStarWarsMod#37]
Mod Version: 1.26 and 1.21
After taming a droid (regular R2D2 one and BB-8), the first right-click causes client to crash. The server doesn't crash. Same configuration works fine in single player. (using forge-1.7.10-10.13.4.1558-1.7.10-universal.jar for the server, but tried other 1.7.10 versions with same results)

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 1/31/16 7:00 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.parzi.starwarsmod.mobs.MobDroidAstromech.func_70085_c(MobDroidAstromech.java:107)
	at net.minecraft.entity.EntityLiving.func_130002_c(EntityLiving.java:1032)
	at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1126)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78768_b(PlayerControllerMP.java:413)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1431)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.parzi.starwarsmod.mobs.MobDroidAstromech.func_70085_c(MobDroidAstromech.java:107)
	at net.minecraft.entity.EntityLiving.func_130002_c(EntityLiving.java:1032)
	at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1126)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78768_b(PlayerControllerMP.java:413)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1431)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['tolchuk'/443, l='MpServer', x=254.90, y=68.62, z=245.37]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (252,64,244), Chunk: (at 12,4,4 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5758 game time, 5758 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 122 total; [EntityClientPlayerMP['tolchuk'/443, l='MpServer', x=254.90, y=68.62, z=245.37], EntitySkeleton['Skeleton'/256, l='MpServer', x=283.50, y=25.00, z=260.50], EntityBat['Bat'/512, l='MpServer', x=268.48, y=27.46, z=189.08], EntityZombie['Zombie'/257, l='MpServer', x=272.34, y=17.00, z=280.34], EntityZombie['Zombie'/258, l='MpServer', x=274.34, y=17.00, z=275.34], EntityCreeper['Creeper'/260, l='MpServer', x=269.97, y=19.00, z=277.34], EntityCreeper['Creeper'/261, l='MpServer', x=275.50, y=17.00, z=274.50], EntitySpider['Spider'/263, l='MpServer', x=288.88, y=34.00, z=283.06], EntitySheep['Sheep'/264, l='MpServer', x=273.53, y=73.00, z=320.66], EntitySheep['Sheep'/265, l='MpServer', x=276.50, y=67.00, z=323.50], EntitySheep['Sheep'/266, l='MpServer', x=275.50, y=69.00, z=321.50], EntitySheep['Sheep'/267, l='MpServer', x=282.78, y=72.00, z=322.25], EntityBat['Bat'/524, l='MpServer', x=318.64, y=18.51, z=210.15], EntitySheep['Sheep'/272, l='MpServer', x=295.47, y=66.00, z=171.47], EntitySheep['Sheep'/273, l='MpServer', x=296.56, y=66.00, z=170.25], EntitySheep['Sheep'/274, l='MpServer', x=294.81, y=66.00, z=173.19], EntitySheep['Sheep'/276, l='MpServer', x=300.94, y=67.00, z=173.97], EntitySkeleton['Skeleton'/277, l='MpServer', x=303.50, y=25.00, z=237.50], EntitySkeleton['Skeleton'/278, l='MpServer', x=301.50, y=25.00, z=238.50], EntityPig['Pig'/280, l='MpServer', x=293.59, y=70.00, z=300.97], EntityPig['Pig'/281, l='MpServer', x=297.81, y=70.00, z=298.19], EntityPig['Pig'/282, l='MpServer', x=296.44, y=70.00, z=299.19], EntityPig['Pig'/283, l='MpServer', x=299.50, y=70.00, z=301.50], EntitySkeleton['Skeleton'/284, l='MpServer', x=301.50, y=17.00, z=322.50], EntityCreeper['Creeper'/293, l='MpServer', x=315.44, y=28.00, z=208.97], EntityCreeper['Creeper'/294, l='MpServer', x=314.50, y=26.00, z=213.50], EntityEnderman['Enderman'/295, l='MpServer', x=311.31, y=26.00, z=218.00], EntityZombie['Zombie'/552, l='MpServer', x=264.44, y=53.00, z=194.94], EntityEnderman['Enderman'/296, l='MpServer', x=312.34, y=26.00, z=214.00], EntityZombie['Zombie'/553, l='MpServer', x=265.31, y=53.00, z=194.75], EntityWitch['Witch'/297, l='MpServer', x=318.06, y=25.00, z=263.56], EntitySkeleton['Skeleton'/554, l='MpServer', x=269.50, y=53.00, z=204.50], EntityWitch['Witch'/298, l='MpServer', x=316.84, y=25.00, z=262.97], EntitySheep['Sheep'/299, l='MpServer', x=308.50, y=70.00, z=305.75], EntityZombie['Zombie'/300, l='MpServer', x=316.50, y=18.00, z=317.50], EntitySheep['Sheep'/301, l='MpServer', x=312.69, y=70.00, z=314.78], EntitySheep['Sheep'/302, l='MpServer', x=307.06, y=70.00, z=306.59], EntitySheep['Sheep'/303, l='MpServer', x=318.72, y=69.00, z=305.50], EntityZombie['Zombie'/304, l='MpServer', x=313.22, y=15.00, z=323.66], EntityZombie['Zombie'/324, l='MpServer', x=328.50, y=42.00, z=248.50], EntitySheep['Sheep'/325, l='MpServer', x=334.50, y=68.00, z=252.50], EntitySheep['Sheep'/327, l='MpServer', x=330.97, y=67.00, z=257.97], EntityBat['Bat'/328, l='MpServer', x=322.75, y=51.00, z=295.92], EntityZombie['Zombie'/331, l='MpServer', x=323.53, y=37.00, z=319.97], EntitySheep['Sheep'/86, l='MpServer', x=186.78, y=63.00, z=287.50], EntitySheep['Sheep'/87, l='MpServer', x=185.50, y=63.00, z=287.19], EntitySheep['Sheep'/88, l='MpServer', x=184.22, y=63.00, z=288.78], EntitySheep['Sheep'/89, l='MpServer', x=187.50, y=64.00, z=289.50], EntityMinecartChest['entity.MinecartChest.name'/95, l='MpServer', x=203.50, y=15.50, z=193.50], EntityItem['item.item.seeds'/96, l='MpServer', x=201.72, y=69.13, z=213.31], EntityVillager['Villager'/97, l='MpServer', x=199.47, y=68.00, z=220.69], EntityVillager['Villager'/98, l='MpServer', x=206.31, y=68.00, z=227.31], EntityBat['Bat'/99, l='MpServer', x=212.94, y=29.00, z=320.13], EntityZombie['Zombie'/102, l='MpServer', x=215.31, y=47.00, z=182.84], EntityBat['Bat'/615, l='MpServer', x=318.63, y=26.01, z=251.53], EntitySkeleton['Skeleton'/104, l='MpServer', x=210.50, y=34.00, z=200.50], EntityVillager['Villager'/105, l='MpServer', x=208.50, y=69.00, z=193.50], EntityVillager['Villager'/106, l='MpServer', x=208.50, y=69.00, z=194.50], EntityVillager['Villager'/107, l='MpServer', x=216.50, y=69.00, z=192.50], EntityVillager['Villager'/108, l='MpServer', x=216.50, y=70.00, z=202.50], EntityVillager['Villager'/109, l='MpServer', x=219.50, y=70.00, z=208.50], EntityVillager['Villager'/110, l='MpServer', x=217.50, y=69.00, z=216.50], EntityVillager['Villager'/111, l='MpServer', x=229.41, y=71.00, z=211.72], EntityVillager['Villager'/112, l='MpServer', x=211.56, y=68.00, z=221.69], EntityVillager['Villager'/113, l='MpServer', x=223.50, y=70.00, z=223.84], EntityVillager['Villager'/114, l='MpServer', x=216.50, y=68.00, z=227.75], EntityVillager['Villager'/115, l='MpServer', x=218.69, y=69.00, z=226.47], EntitySheep['Sheep'/116, l='MpServer', x=209.50, y=66.00, z=302.50], EntitySheep['Sheep'/117, l='MpServer', x=212.50, y=65.00, z=297.47], EntitySheep['Sheep'/118, l='MpServer', x=218.75, y=69.00, z=299.47], EntitySheep['Sheep'/119, l='MpServer', x=212.53, y=65.00, z=298.63], EntityCreeper['Creeper'/130, l='MpServer', x=251.97, y=43.00, z=196.53], EntityZombie['Zombie'/131, l='MpServer', x=215.31, y=47.00, z=183.63], EntitySkeleton['Skeleton'/132, l='MpServer', x=227.31, y=53.00, z=209.47], EntityZombie['Zombie'/133, l='MpServer', x=220.75, y=56.00, z=212.59], EntityVillager['Villager'/135, l='MpServer', x=230.50, y=73.00, z=208.50], EntityVillager['Villager'/136, l='MpServer', x=231.50, y=73.00, z=208.50], EntityVillager['Villager'/137, l='MpServer', x=225.78, y=71.00, z=215.38], EntityVillager['Villager'/138, l='MpServer', x=225.50, y=71.00, z=206.75], EntityVillager['Villager'/139, l='MpServer', x=227.66, y=71.00, z=212.00], EntitySkeleton['Skeleton'/140, l='MpServer', x=239.49, y=38.69, z=250.34], EntityBat['Bat'/175, l='MpServer', x=251.88, y=57.10, z=169.72], EntityBat['Bat'/176, l='MpServer', x=252.28, y=55.10, z=174.47], EntityItem['item.tile.gravel'/177, l='MpServer', x=248.13, y=14.13, z=187.38], EntityItem['item.tile.gravel'/178, l='MpServer', x=249.06, y=14.13, z=189.56], EntityItem['item.tile.gravel'/179, l='MpServer', x=248.88, y=14.13, z=186.97], EntityItem['item.tile.rail'/180, l='MpServer', x=248.22, y=14.13, z=197.72], EntityZombie['Zombie'/181, l='MpServer', x=255.50, y=31.00, z=205.50], EntityItem['item.item.seeds'/183, l='MpServer', x=250.31, y=66.13, z=217.09], MobDroidAstromech['Astromech Droid'/184, l='MpServer', x=254.84, y=67.00, z=242.59], EntitySkeleton['Skeleton'/186, l='MpServer', x=252.47, y=26.00, z=267.03], EntityItem['item.tile.flower1.dandelion'/187, l='MpServer', x=248.63, y=63.13, z=278.56], EntityItem['item.tile.flower1.dandelion'/188, l='MpServer', x=243.25, y=64.13, z=278.66], EntityItem['item.item.seeds'/189, l='MpServer', x=244.75, y=64.13, z=277.31], EntitySquid['Squid'/190, l='MpServer', x=251.47, y=62.34, z=287.66], EntityZombie['Zombie'/702, l='MpServer', x=264.50, y=47.00, z=220.50], EntitySkeleton['Skeleton'/703, l='MpServer', x=269.50, y=47.00, z=209.50], EntityBat['Bat'/452, l='MpServer', x=214.63, y=23.79, z=200.66], EntityBat['Bat'/455, l='MpServer', x=217.47, y=23.01, z=202.31], EntitySheep['Sheep'/211, l='MpServer', x=258.03, y=66.00, z=218.91], EntitySheep['Sheep'/212, l='MpServer', x=269.53, y=67.00, z=228.66], EntitySheep['Sheep'/213, l='MpServer', x=270.91, y=67.00, z=229.94], EntityEnderman['Enderman'/214, l='MpServer', x=272.63, y=20.00, z=244.25], EntityZombie['Zombie'/215, l='MpServer', x=270.09, y=20.00, z=249.38], EntityZombie['Zombie'/216, l='MpServer', x=271.66, y=20.00, z=245.03], EntitySkeleton['Skeleton'/217, l='MpServer', x=261.50, y=20.00, z=254.09], EntitySpider['Spider'/219, l='MpServer', x=265.81, y=20.00, z=254.72], EntityZombie['Zombie'/220, l='MpServer', x=269.44, y=20.00, z=286.47], EntitySquid['Squid'/221, l='MpServer', x=258.50, y=61.34, z=281.50], EntitySquid['Squid'/222, l='MpServer', x=266.75, y=61.00, z=294.16], EntitySquid['Squid'/223, l='MpServer', x=262.41, y=61.00, z=294.19], EntitySquid['Squid'/224, l='MpServer', x=254.44, y=61.84, z=293.50], EntitySquid['Squid'/225, l='MpServer', x=271.47, y=62.34, z=288.81], EntitySheep['Sheep'/228, l='MpServer', x=261.56, y=66.00, z=324.34], EntityZombie['Zombie'/248, l='MpServer', x=287.50, y=55.00, z=174.50], EntityCreeper['Creeper'/249, l='MpServer', x=281.16, y=19.00, z=192.75], EntityCreeper['Creeper'/250, l='MpServer', x=287.50, y=19.00, z=192.50], EntitySheep['Sheep'/252, l='MpServer', x=275.91, y=67.00, z=221.91], EntitySkeleton['Skeleton'/253, l='MpServer', x=270.44, y=19.00, z=248.47], EntityZombie['Zombie'/254, l='MpServer', x=280.50, y=25.00, z=261.50], EntitySkeleton['Skeleton'/255, l='MpServer', x=291.53, y=26.00, z=261.09], EntityBat['Bat'/511, l='MpServer', x=266.55, y=24.80, z=182.44]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 103859544 bytes (99 MB) / 336580608 bytes (320 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	starwarsmod{1.2.0} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.2.1.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.1001' Renderer: 'AMD Radeon (TM) R9 390 Series'
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon (TM) R9 390 Series GL version 4.5.13416 Compatibility Profile Context 15.300.1025.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by tolchuk** [comment]
Hi parzivail,

Just wanted to say thank you and tell you my 8 year old daughter was overjoyed to find a bug. :) :+1:

**Comment by parzivail** [comment]
@tolchuk Glad to hear it! We need all the help we can get :D

**Comment by parzivail** [comment]
Fixed in 1.2.7 :D
