### ISSUE TITLE
Question from the Russian fan.

### ISSUE THREAD

**Issue by NaomiVezer** [Parzivail-Modding-Team/ParziStarWarsMod#38]
Will add Pods? Please, it is necessary! с:
And  add Sith and Jedi (mobs)
![carreras-pods-star-wars-](https://cloud.githubusercontent.com/assets/17001045/12711737/3c688cdc-c8d3-11e5-9e40-49beaa4b677a.jpg)

In it to a fashion is a lot of interesting. Panzi's Star Wars will be the best if in it there will be elements from this a fashion (mod). I am sorry for my bad English :с
http://minecraft-inside.ru/mods/9063-star-wars-mod.html

**Comment by parzivail** [comment]
It's definitely on our to-do list when we make the prequel trilogies
