### ISSUE TITLE
HALP!

### ISSUE THREAD

**Issue by zorro290** [Parzivail-Modding-Team/ParziStarWarsMod#4]
I need quick help right now.....
what do i need to do to get the next part of my jedi training done? yoda said to come back when i can grab enemies with the force, but i dont know how! please help me......
and yes i read the post.

-zorro290

**Comment by parzivail** [comment]
Either you didn't read the post or you're illiterate. It says to _visit somewhere else instead_ and to not post issues here. Go read it again and follow the link.

**Comment by grepwood** [comment]
You got some chip on your shoulder to insult your users @parzivail and point them to some noname server on non-443 port.

**Comment by MrPickles2009** [comment]
I don't know which link you clicked on @grepwood but the issues site is still up [here]( http://52.90.255.138:8080/projects/PSWM/issues/PSWM-31?filter=allopenissues)

They did recently shutdown support for the mod so I don't know how long that link will be up for

**Comment by parzivail** [comment]
@grepwood We're hosting the server ourselves. SSL doesn't matter because you don't have to log in. If you're scared someone is going to snoop on the data you're sending about an issue with a Minecraft mod, don't post an issue.
