### ISSUE TITLE
Client crash when using hyperdrive while wearing Jedi robe.

### ISSUE THREAD

**Issue by Momibelle** [Parzivail-Modding-Team/ParziStarWarsMod#46]
Mod Version 1.2.8
Description:
Client crashes when you are wearing a robe and try to use a hyperdrive. Server does not crash but console shows the following ...

10.02 07:01:31 [Server] ERROR SimpleChannelHandlerWrapper exception
10.02 07:01:31 [Server] INFO java.lang.NullPointerException
10.02 07:01:31 [Server] INFO at com.parzivail.pswm.network.MessageRobesIntNBT.handleMessage(MessageRobesIntNBT.java:30) ~[MessageRobesIntNBT.class:?]

We are running the mod with KCauldron-1.7.10-2.1403.1.54 (have to run with particular plugins to aid play for the 8-10 year -old set!).

**Comment by parzivail** [comment]
Thanks, we'll look into a fix.

**Comment by parzivail** [comment]
@Momibelle Yuck! I figured out what's up. Turns out that the server is still trying to give you some Force XP while you're inter-dimension, and it doesn't know where to look for you. Pretty sure it's fixed now, we plan to have another patch release this weekend.

**Comment by Momibelle** [comment]
Thanks so much!

**Comment by parzivail** [comment]
We still need to publicly verify the fix (we'll release this weekend, but I want to keep the issue open to remind me), sorry :P
