### ISSUE TITLE
[enchancement] sword faces

### ISSUE THREAD

**Issue by Alexismachina** [Parzivail-Modding-Team/ParziStarWarsMod#51]
Mod Version 1.2.9
Client side
the kyloren sword is currently this way http://i.imgur.com/OM3IIBQ.png and look a tiny bit weird.
could it be possible to make the sword face like a vanilla sword, a.k.a like show in the picture here http://i.imgur.com/gW6sVp8.png , also the new ligthsaber look really cool

**Comment by weastonmiller** [comment]
We made it face that way on purpose, if you held a crossguard emitting lightsaber anyway except the way we have it, you would stab yourself in the arm when you try to swing it/hold it (not in the mod, in the actual universe).

**Comment by Alexismachina** [comment]
ok thx
