### ISSUE TITLE
Desync issue with sith ligtning powers

### ISSUE THREAD

**Issue by Alexismachina** [Parzivail-Modding-Team/ParziStarWarsMod#52]
Version 1.2.9
Sometimes the sith power desync , especially with ligtning power even when not activated when you are close to any mob it still produces ligthning without damaging them
The picture below is an example
http://i.imgur.com/qLzSB3N.png

**Comment by Alexismachina** [comment]
*Note it also happens with ligthsabers, the ligthsaber closes and doesnt open until a relog that it will just not open

**Comment by parzivail** [comment]
@Alexismachina Are you on a server?

**Comment by Alexismachina** [comment]
@parzivail i tried both and it did it

**Comment by parzivail** [comment]
@Alexismachina are there any messages printed to the log ever?

**Comment by Alexismachina** [comment]
Nope the log couldn't be cleaner
