### ISSUE TITLE
When using blasters I crash

### ISSUE THREAD

**Issue by LalaLoopsy** [Parzivail-Modding-Team/ParziStarWarsMod#54]
Mod version I'm using is 1.2.9
Client and server are 1.7.10
I'm running my own server.
When someone in the server tries to rightclick while having a blaster in hand, they crash. And we cannot see lightsabers or spawn ships.

---- Minecraft Crash Report ----
// Oops.

Time: 14-2-16 18:58
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.parzivail.pswm.items.weapons.ItemSequelBlasterRifle.func_77659_a(ItemSequelBlasterRifle.java:143)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.parzivail.pswm.items.weapons.ItemSequelBlasterRifle.func_77659_a(ItemSequelBlasterRifle.java:143)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Deef'/1893, l='MpServer', x=-102,85, y=70,99, z=236,43]]
	Chunk stats: MultiplayerChunkCache: 936, 936
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-112,64,247), Chunk: (at 0,4,7 in -7,15; contains blocks -112,0,240 to -97,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 15896 game time, 15896 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 30 total; [EntityClientPlayerMP['Deef'/1893, l='MpServer', x=-102,85, y=70,99, z=236,43], EntityChicken['Chicken'/128, l='MpServer', x=-23,66, y=64,00, z=284,44], EntitySquid['Squid'/833, l='MpServer', x=-136,50, y=60,00, z=268,88], EntityOtherPlayerMP['Danielz'/199, l='MpServer', x=-98,50, y=66,00, z=285,03], EntityBat['Bat'/1604, l='MpServer', x=-120,23, y=32,07, z=168,80], EntitySquid['Squid'/1988, l='MpServer', x=-162,81, y=60,13, z=213,59], EntitySquid['Squid'/1989, l='MpServer', x=-163,50, y=60,00, z=216,50], EntitySquid['Squid'/1990, l='MpServer', x=-159,66, y=62,34, z=206,78], EntitySquid['Squid'/1992, l='MpServer', x=-99,81, y=61,25, z=174,63], EntitySquid['Squid'/1993, l='MpServer', x=-97,69, y=61,22, z=175,69], EntitySquid['Squid'/1994, l='MpServer', x=-95,69, y=60,91, z=175,91], EntityChicken['Chicken'/143, l='MpServer', x=-31,44, y=64,00, z=279,53], EntityBat['Bat'/2065, l='MpServer', x=-181,45, y=30,95, z=157,06], EntityBat['Bat'/1884, l='MpServer', x=-44,50, y=29,05, z=230,69], EntityBat['Bat'/1756, l='MpServer', x=-170,53, y=31,10, z=303,25], EntityBat['Bat'/1885, l='MpServer', x=-38,47, y=26,48, z=236,81], EntityBat['Bat'/1958, l='MpServer', x=-74,56, y=39,59, z=220,75], EntityBat['Bat'/1575, l='MpServer', x=-146,09, y=25,10, z=270,91], EntityBat['Bat'/1964, l='MpServer', x=-164,25, y=48,95, z=249,31], EntityBat['Bat'/1965, l='MpServer', x=-78,09, y=29,51, z=258,13], EntitySquid['Squid'/1583, l='MpServer', x=-135,25, y=61,31, z=208,69], EntityBat['Bat'/2039, l='MpServer', x=-60,34, y=32,13, z=252,25], EntityChicken['Chicken'/122, l='MpServer', x=-31,50, y=63,00, z=209,50], EntityChicken['Chicken'/123, l='MpServer', x=-30,59, y=63,00, z=215,47], EntityCow['Cow'/60, l='MpServer', x=-178,47, y=68,00, z=297,50], EntityChicken['Chicken'/125, l='MpServer', x=-31,63, y=63,00, z=259,59], EntityBat['Bat'/1214, l='MpServer', x=-85,59, y=48,10, z=219,72], EntityChicken['Chicken'/126, l='MpServer', x=-28,91, y=64,00, z=274,34], EntityCow['Cow'/62, l='MpServer', x=-179,50, y=73,00, z=300,50], EntityChicken['Chicken'/127, l='MpServer', x=-28,44, y=64,00, z=267,56]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 181571936 bytes (173 MB) / 419123200 bytes (399 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	starwarsmod{1.2.9} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.2.9.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.75' Renderer: 'GeForce GTX 750/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 750/PCIe/SSE2 GL version 4.5.0 NVIDIA 361.75, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by weastonmiller** [comment]
How consistent is the crash? And could you give us more details about the lightsaber and ship problems?

**Comment by LalaLoopsy** [comment]
Well. Whenever either me, the server owner, or my friend try to spawn a ship, or shoot with a blaster. We just crash, right away. We do not see blaster bolts either, nor do we see the lasers of the lightsabers. We crash each and every single time, no exceptions. The crash report is seen above.

Basically what we've done is, we ran ourselves a private server for us alone through the forge client. Both the client and the server I run have the same Parzi's Star Wars mod version though. We did this by just putting the .jar file of the mod in the mod folder of the client and the server. 

Did I do something wrong? Maybe it's a memory issue of the server by chance? The server only runs like 1gb. I can increase it to more though, but that would mean I'd have to run it on my 64bit PC instead of my 32bit laptop. 

Just let me know how to fix this or if it's fixed. :)

**Comment by parzivail** [comment]
This seems to be fixed in 1.2.10

**Comment by LalaLoopsy** [comment]
Alright. When will that be?

**Comment by parzivail** [comment]
Probably soon, no exact date right now
