### ISSUE TITLE
Kylo Ren lightsaber glitch

### ISSUE THREAD

**Issue by InfektOG** [Parzivail-Modding-Team/ParziStarWarsMod#57]
I don´t know if it's intended but Kylo´s lightsaber doesn´t get the glow effect.

**Comment by weastonmiller** [comment]
Could you show us some screenshots? Are you sure you're using 1.2.10?

**Comment by Alexismachina** [comment]
It could be a cross mod interaction what is the list of mod ?

**Comment by InfektOG** [comment]
![2016-02-22_19 26 53](https://cloud.githubusercontent.com/assets/17413760/13229783/6a827a9c-d99a-11e5-8609-32454dfa834e.png)
![2016-02-22_19 26 28](https://cloud.githubusercontent.com/assets/17413760/13229784/6e10a80a-d99a-11e5-9986-761a0e799939.png)

In my opinion should be brighter.
If we compare with this lightsaber.
![2016-02-22_18 38 38](https://cloud.githubusercontent.com/assets/17413760/13229817/9329a858-d99a-11e5-8157-57f4d713f8d5.png)

**Comment by Alexismachina** [comment]
Yeah, they don't seem to glow at all ;-;

**Comment by Alexismachina** [comment]
What's the list of mods ?

**Comment by weastonmiller** [comment]
We double checked that all of them glowed before release, we'll see what we can find, but it glows for us.

**Comment by Alexismachina** [comment]
@weastonmiller it glows on our server too...

**Comment by weastonmiller** [comment]
What kind of graphics card do you have? Or are your graphics integrated and not separate?

**Comment by Alexismachina** [comment]
oh! do you have optifine ?

**Comment by InfektOG** [comment]
Yes I have.

**Comment by Alexismachina** [comment]
That migth what causes this...

**Comment by InfektOG** [comment]
Integrated graphic card.

**Comment by weastonmiller** [comment]
Might be optifine, it doesn't like our suns and moons either.

**Comment by weastonmiller** [comment]
Integrated could be the problem too, we found out pretty quickly that the glow doesn't work for all integrated graphics, it will definitely work for a separate dedicated card, but not all integrated. Let us know if turning off optifine helps

**Comment by InfektOG** [comment]
I will check that out

**Comment by Alexismachina** [comment]
Tough also i think he makes a point on the kylo ren saber not having a ligth red color.

**Comment by InfektOG** [comment]
Nope remains the same.

**Comment by weastonmiller** [comment]
Hmm, well again we'll look, but no promises. It probably has to do with integrated graphics, the laptop I use won't show glow for any of them cause it has integrated graphics

**Comment by InfektOG** [comment]
Mine actually glows on the red , blue and green lightsaber but not on Kylo's lightsaber.

**Comment by weastonmiller** [comment]
None glow for me, but they glow for Parzi. Idk what the problem is, could be that the kylo has more surface area to apply the fragment shader too and it wants more power from the graphics. We'll see what we can do though.

**Comment by Alexismachina** [comment]
The ligthsaber should also put ligth in front of the player rigth ?

**Comment by weastonmiller** [comment]
No the lightsaber is not a light source

**Comment by InfektOG** [comment]
Well hope you´ll find the solution.Thanks for answering Mr.Weaston :)

**Comment by parzivail** [comment]
Kylo doesnt work for some graphics cards, sorry

**Comment by InfektOG** [comment]
That´s ok Mr.Parzivail
