### ISSUE TITLE
Issues Traveling to other planets

### ISSUE THREAD

**Issue by RazzleberryFox** [Parzivail-Modding-Team/ParziStarWarsMod#6]
We are having problems moving from planets using the hyperdrives, from earth to tatooine it was fine, but when we tried traveling back to earth or other planets we would get kicked from the server.

http://pastebin.com/LyQJzv6m

**Comment by RazzleberryFox** [comment]
I deleted the whole worldsave and started a new one, the bug is... gone, It might be due to world corruption?

**Comment by parzivail** [comment]
well, our testing has proved that it's most likely due to save/quit and re-loading the world without actually closing the game. we may have fixed it, but rigorous testing is currently underway

**Comment by RazzleberryFox** [comment]
Happened again. When we came back online, all teleporting to dimensions was broken. So a reloading issue possibly...

**Comment by RazzleberryFox** [comment]
Ok! We know something new! Apparently it is the user save file. Upon disconnecting the data gets corrupted somehow. Deleting the player data file fixes the issue, and you are able to teleport just fine, as long as you do not log off again.

**Comment by weastonmiller** [comment]
This issue is fixed in 1.2.0, downloads are [here](http://parzivail.com/mods/tswm/download.html)
