### ISSUE TITLE
There is no instructions on what the default key bind is to use your selected force power?

### ISSUE THREAD

**Issue by Maolink** [Parzivail-Modding-Team/ParziStarWarsMod#6]
I looked through the controls menu and there was no key bind for using the selected force power. i have force push equipped but no matter what buttons i push i can't use it

**Comment by weastonmiller** [comment]
I don't remember what it is off the top of my head, but you can change it in the vanilla controls menu.  I think the default may be C or X or something around there.

**Comment by Maolink** [comment]
Ive figured it out, the key bind option is labeled as "use robe force power" even though I'm not using a version that uses robes for force powers. I think the key bind label is outdated is all.
