### ISSUE TITLE
Z6 riot control baton

### ISSUE THREAD

**Issue by Lukalot** [Parzivail-Modding-Team/ParziStarWarsMod#61]
You should add the Z6 riot control baton, which is the weapon that FN-2199 used when attacking fin, here:
http://starwars.wikia.com/wiki/Z6_riot_control_baton

It was used to shock or pummel an opponent, so it might be good for a touch of extra knock-back or something like that.

![latest](https://cloud.githubusercontent.com/assets/15091862/13430821/b02d323a-df94-11e5-87e5-81bcf9003f04.jpg)

**Comment by Lukalot** [comment]
Just thought that would be a good extra touch to the new first order stuff.

**Comment by weastonmiller** [comment]
Please don't open issues for suggestions or feature requests, post them on our site on the Suggest A Feature page, or send us a message or post to our Minecraft Forum thread, thank you.

**Comment by Lukalot** [comment]
Luke,

Weston Miller sent you this message;

**Comment by Lukalot** [comment]
oh, sorry :) So should I repost it there or would you rather me just leave it here now that its done?

**Comment by weastonmiller** [comment]
Leave it here, just know for future reference.
