### ISSUE TITLE
Crash Report - Parzi's Star Wars Mod

### ISSUE THREAD

**Issue by AgentDempsey** [Parzivail-Modding-Team/ParziStarWarsMod#62]
Mod Version: 1.2.10

I was launching my game, and the MC window showed up and said it was loading Parzi's Star Wars Mod (it was the only mod in there) and it just closed and the crash window showed up.

I was playing on MC client 1.7.10 Forge (recommended AND latest [but not at the same time]).

[crash-2016-03-04_06.02.37-client.txt](https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/files/158564/crash-2016-03-04_06.02.37-client.txt)

**Comment by parzivail** [comment]
That... that's weird. Try installing Java 8 (link on our downloads page)

**Comment by icreatebuilds** [comment]
Dear Colby,
I work for Mojang and all you need to do is reinstall the mod your file has
been corrupted

**Comment by parzivail** [comment]
@icreatebuilds I understand that, but our mod required Java 8, and @AgentDempsey is using Java 7

**Comment by icreatebuilds** [comment]
Yes but I read the whole crash report and he had a corrupt file he needs to
install 8 then download a new one

**Comment by parzivail** [comment]
@icreatebuilds I *understand* that but the best methodology when dealing with a problem is one step at a time, even if you know the cause. fix all you can.

**Comment by icreatebuilds** [comment]
Yes I understand but you must download java then a new file of the mod

**Comment by icreatebuilds** [comment]
That is true first install Java 8 then get a new mod file

**Comment by AgentDempsey** [comment]
Listen! I tried updating my Java and my PC crashed so I had to reinstall Java. It should be done by this afternoon, Wednesday March 9 2016. When I get home from school I will try it again.

**Comment by AgentDempsey** [comment]
Also, my internet is from DISH so it SUCKS. It takes a **very** long time to download. I will repost if something good or bad happens, just to let y'all know.

**Comment by weastonmiller** [comment]
Awesome, we'll look out for the update
