### ISSUE TITLE
blocks tmp

### ISSUE THREAD

**Issue by Luke4tex** [Parzivail-Modding-Team/ParziStarWarsMod#65]
i'm using the latest version of the mod and the 1.7.10 version minecraft forge, and some of the blocks are tmp. and i guess that the holotables are also tmp, because i can't find them in my inventory.
is there a solution for this problem?

**Comment by weastonmiller** [comment]
Not a problem, most of the decoration blocks are creative only for now. As many as possible will have crafting recipes in 1.3 which is a few months out.
