### ISSUE TITLE
Log-on with old abilities

### ISSUE THREAD

**Issue by Momibelle** [Parzivail-Modding-Team/ParziStarWarsMod#67]
When we log into the game, we have the 'old' abilities from the previous version, such as fly.
I'm not sure if it's from the jet-pack or the Jedi robe.
Kinda ignored it, until now. 
Priority: low (because most people are not updating a server, but playing each version anew, as you release).
Happy Easter!
Anna

**Comment by parzivail** [comment]
Yuck! Sounds like a jetpack issue possibly, so try getting them to put on then take off a jetpack. If that doesn't work, do players have items and stuff on them? If so, tell them to dump their stuff into chests and then delete their playerdata files (`world_save/playerdata/<uuid>.dat`). Should help :D

**Comment by Momibelle** [comment]
Oh ya! That should work ... (on both counts).
: )
thx
anna

**Comment by parzivail** [comment]
Happy easter!
