### ISSUE TITLE
Jedi robes won't level up past 35.

### ISSUE THREAD

**Issue by mathesto74** [Parzivail-Modding-Team/ParziStarWarsMod#68]
I put myself in a creative flatworld to test out the different jedi/sith powers and found that in almost every occasion when I leveled past 35 I would be asked to choose a side and then be immediately put back at level 34 and have all previous point allocations removed. I have been using command blocks the majority of the time, with commands which summon xp orbs, although I have tried the long way by killing mobs repetitively. In either case, the problem occurs. 

I have thus far very much enjoyed the mod, and I thank you for your efforts on it, but I'm hoping that this would be addressed in the near future. I will test the robes again for myself in a normal world by getting them legit, and I'm hoping that it is only my methods which caused the issue, but I am at this moment unsure.

Thank you.

**Comment by parzivail** [comment]
Huh, that's peculiar. Are there any messages printed to the log?

**Comment by mathesto74** [comment]
I was in single player, and it did not crash, so I don't believe there were any logs.

**Comment by parzivail** [comment]
Huh, that's weird. I'll look into it and see if I can reproduce it

**Comment by mathesto74** [comment]
Alright, sounds good. Thank you.

**Comment by parzivail** [comment]
I migrated this issue to the new issue tracker, so I'm closing this one. see the last remaining issue for more info.
