### ISSUE TITLE
Defend Force Power

### ISSUE THREAD

**Issue by unblazoned** [Parzivail-Modding-Team/ParziStarWarsMod#69]
on a server i had leveled up to the sith acolyte and spent 30 points on the defend force power, and when i used it a wampa hit me and killed me. but i wasn't dead. i had the death animation (reddish color on my body) i had zero hearts and my screen was shaking like i was in an earthquake. but i was still able to walk and use items, however i couldn't open my inventory or use any blocks like chests crafting tables etc. so i did /kill and the problem was solved... or so i thought. now every time i get hit i die right away and it does the same thing. please figure out whats wrong and fix it.

**Comment by unblazoned** [comment]
here are some screenshots

http://imgur.com/a/05QgQ

**Comment by parzivail** [comment]
2 things real quick:
* What java version are you using?
* Does the server have the mod installed as well? What version of java are _they_ using?

**Comment by unblazoned** [comment]
I am using Java 8 update 74 and the server uses Java 8 77 and the mod version is 1.2.10

**Comment by parzivail** [comment]
Alright, sounds like a wampa bug. I'll look into it

**Comment by unblazoned** [comment]
Well there was another guy on the server that had the same thing happening to him but he never went to hoth.

**Comment by parzivail** [comment]
@unblazoned Does it happen without the mod or on other servers? I know it's an inherently MC vanilla bug, it may just be more prone here

**Comment by unblazoned** [comment]
I'm not sure about others servers cause I've only played on the one. we banned the item and reset the server so the problem hasn't come up since. I'll try and recreate the issue in single player and let you know if it's just on servers.

**Comment by parzivail** [comment]
I migrated this issue to the new issue tracker, so I'm closing this one. see the last remaining issue for more info.
