### ISSUE TITLE
Version checker bug

### ISSUE THREAD

**Issue by SOL3675** [Parzivail-Modding-Team/ParziStarWarsMod#7]
It's not a serious bug, but I noticed a little one.
It has no problem with gameplay. Just inform you :D
![vc bug](https://cloud.githubusercontent.com/assets/16431933/11998418/0d2e5f1e-aae2-11e5-9bb9-a96831343f72.png)

**Comment by weastonmiller** [comment]
Thanks for letting us know, we forgot to fix that code before we pushed 1.2.0.  We'll probably fix it sometime soon with some other small changes changes in some form of patch.  Thanks again for keeping us updated.
