### ISSUE TITLE
Please, add something more to the Jedi/Sith storylines. Sith especailly

### ISSUE THREAD

**Issue by Maolink** [Parzivail-Modding-Team/ParziStarWarsMod#7]

**Comment by Maolink** [comment]
Theres nothing to the storylines, you just go to them, they offer to teach you, you accept, they teach you to create a lightsaber, talk a bit, then you're done. Its incredibly boring and like there to be a bit more. Maybe the grand master reacts to you turning to the dark side. Maybe theres a bit where the Sith Master tells you some grand secret of the Force and you level your force up faster. I dunno, but you guys have literal magic space wizards to work with here, please please please, make it interesting!

**Comment by weastonmiller** [comment]
I apologize for not giving a better answer, but we discontinued the development of this mod a month or 2 ago.  There will unfortunately be no more updating, but we do agree that the questing wasn't as exciting as it could have been.
