### ISSUE TITLE
Server crashes when I log in.

### ISSUE THREAD

**Issue by RazzleberryFox** [Parzivail-Modding-Team/ParziStarWarsMod#71]
Ok so, I updated the starwars mod from 1.2.0 to 1.2.11 (yes I know I skipped a ton of versions, I hadn't played in a while). 

The instant I log onto the server I get a SERVER crash and get a "ticking entity" crash report.
I am running Forge server version 1.7.10-10.13.4.1566

Crash Log: http://pastebin.com/jxHHeHX9

**Comment by parzivail** [comment]
[tried to respond via email but aparrantly email is being dumb so sorry if this is a dupe]

It seems the progressive mob changes that we made over the course of the eleven updates was enough to corrupt the mobs when applied all at once. The best way I know of to remedy this would be to create a new world with the same seed and MCEdit in any structures and such you had built.

**Comment by parzivail** [comment]
It seems the progressive mob changes that we made over the course of the
eleven updates was enough to corrupt the mobs when applied all at once. The
best way I know of to remedy this would be to create a new world with the
same seed and MCEdit in any structures and such you had built.

**Comment by parzivail** [comment]
I migrated this issue to the new issue tracker, so I'm closing this one. see the last remaining issue for more info.
