### ISSUE TITLE
read this

### ISSUE THREAD

**Issue by broman216** [Parzivail-Modding-Team/ParziStarWarsMod#76]
make a with robe i didn't know how to leave request so i did on this and with robes and mor with and dark sir things please lease or i will delete them od please i love the dark side

**Comment by weastonmiller** [comment]
Thanks, sith robes are already on our to-do list.

**Comment by broman216** [comment]
what about making your own custom lightsabers

**Comment by weastonmiller** [comment]
Almost done with our own system at the moment
