### ISSUE TITLE
Jedi Master

### ISSUE THREAD

**Issue by 2019jaylee** [Parzivail-Modding-Team/ParziStarWarsMod#78]
I can;t find him, and i have spend 20 minutes trying to find him but i couldn't so could you at least post a picture of him?
and is it right that he is in a city that we see when we go to tatooine?

**Comment by 2019jaylee** [comment]
ALSO i found imperial and rebel recruiter but they do not have any QUEST!

**Comment by parzivail** [comment]
Please read "READ THIS before posting an issue!" #72
