### ISSUE TITLE
Grass Side Texture Issue

### ISSUE THREAD

**Issue by TheTimeLord161** [Parzivail-Modding-Team/ParziStarWarsMod#8]
![2015-12-26_15 25 44](https://cloud.githubusercontent.com/assets/16447134/12007836/feae72b8-abe4-11e5-90ee-75a3703d5277.png)

I have your mod installed with just optifine aside from it and the sides of the grass texture all look like this. I have put settings on fancy and it didn't help.

**Comment by weastonmiller** [comment]
Sorry for not understanding, but what exactly is the problem?

**Comment by parzivail** [comment]
If you're worried that it's not solid grass on the sides, you may instead be looking for [BetterFoliage](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2119722-better-foliage) instead of OptiFine.

**Comment by TheTimeLord161** [comment]
Sorry for the poorly written post, I was just wondering why the sides of the grass aren't matching to the top. The side textures are bright and the side textures aren't, it happens for whatever biome it is in.

**Comment by weastonmiller** [comment]
@TheTimeLord161 We did that on purpose in a few biomes to make it feel different, it looks like we forgot to fix the sides though.  Thanks for letting us know.
