### ISSUE TITLE
The game crashed whilst unexpected error

### ISSUE THREAD

**Issue by YourRealCunt** [Parzivail-Modding-Team/ParziStarWarsMod#8]
Hey im trying to launch the game/mod and it says The game crashed whilst unexpected error
and i have the forge mod 1.7.10 and no other mod in the mods folder and i dont know what to do

**Comment by timoreo22** [comment]
Game Crash log?
can be helpful.
win + R and paste this %USERPROFILE%\AppData\Roaming\.minecraft\crash-reports
then get the log with the correct date :)

**Comment by parzivail** [comment]
Closed due to
1) Inactivity
2) Us not supporting the mod anymore
