### ISSUE TITLE
Why you left PSWM?

### ISSUE THREAD

**Issue by Yakna** [Parzivail-Modding-Team/ParziStarWarsMod#9]
This is a simple question: Why you left PSWM? Technic problems? Didn't want to work on it anymore? No ideas?

And if somebody reads this: Could you please update this mod with new things? Everyone would appreciate it. Like adding better physics, more vehicles, etc...

**Comment by parzivail** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2507627-parzis-star-wars-mod-v1-3-0-the-force-awakens?comment=2849
