### ISSUE TITLE
Crash on Win10

### ISSUE THREAD

**Issue by Timeout-VIE** [Parzivail-Modding-Team/ParziStarWarsMod#9]
using Win10 with Forge 1.7.10 - 10.13.4.1558
During "Creating World" the screen switches to "Shutting down internal server" with attached crash report and latest.log

![2015-12-28_21h41_56](https://cloud.githubusercontent.com/assets/16468230/12025542/40f6ef66-adb0-11e5-8c4f-de1b857812c7.png)
![2015-12-28_21h52_54](https://cloud.githubusercontent.com/assets/16468230/12025544/40ffa714-adb0-11e5-9b3d-a9c85dc1b0ee.png)
![2015-12-28_21h53_58](https://cloud.githubusercontent.com/assets/16468230/12025543/40f8bf3a-adb0-11e5-8b0f-dae0c13bbb24.png)
![2015-12-28_22h06_26](https://cloud.githubusercontent.com/assets/16468230/12025541/40f6e5d4-adb0-11e5-91b9-8a043e322138.png)
[crash-2015-12-28_22.06.30-client.txt](https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/files/73543/crash-2015-12-28_22.06.30-client.txt)
[latest.txt](https://github.com/Parzivail-Modding-Team/ParziStarWarsMod/files/73545/latest.txt)

**Comment by parzivail** [comment]
I have no idea where you got Forge v7.10.99.99, but try downloading the recommended version from [here](http://files.minecraftforge.net/maven/net/minecraftforge/fml/index_1.7.10.html)

**Comment by weastonmiller** [comment]
I'm using 10.13.4.1448, there must be some issue with that specific version (.1558) that you're using, let us know when you get it working.  Thanks.

**Comment by securitypedant** [comment]
I have the mod running with forge-1.7.10-10.13.4.1558-1.7.10-universal.jar and do not have any crash.

**Comment by parzivail** [comment]
The issue is most likely related to a faulty version of forge, try using a different one.
